const fs = require('fs')
const path = require('path')

const agentsDir = path.join(__dirname, '..')
const outFile = path.join(agentsDir, 'src', 'prompts.ts')

function read(agent, filename) {
  const file = path.join(agentsDir, agent, `${filename}.md`)
  try {
    return fs.readFileSync(file, 'utf-8')
  } catch (e) {

    process.exit(1)
  }
}

function esc(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')
}

const shared = {
  globalSystemPrompt: read('_shared', 'global-system-prompt'),
  monetizationTriggerTemplate: read('_shared', 'monetization-trigger'),
  crossPromoRaw: read('_shared', 'cross-promo'),
  academyPromoRaw: read('_shared', 'academy-promo'),
}

const agents = ['luna', 'arcas', 'numi', 'umbra']

const systemPrompts = {}
const firstMessages = {}
const instagramPrompts = {}

for (const agent of agents) {
  systemPrompts[agent] = read(agent, 'system-prompt')
  firstMessages[agent] = read(agent, 'first-message')
  instagramPrompts[agent] = read(agent, 'instagram-content')
}

let output = `// Auto-generated by scripts/build-prompts.js\n// Do not edit manually\n\n`

for (const [key, value] of Object.entries(shared)) {
  output += `export const ${key} = \`${esc(value)}\`\n\n`
}

output += `export const agentSystemPrompts: Record<string, string> = {\n`
for (const agent of agents) {
  output += `  ${agent.toUpperCase()}: \`${esc(systemPrompts[agent])}\`,\n`
}
output += `}\n\n`

output += `export const agentFirstMessageTemplates: Record<string, string> = {\n`
for (const agent of agents) {
  output += `  ${agent.toUpperCase()}: \`${esc(firstMessages[agent])}\`,\n`
}
output += `}\n\n`

output += `export const agentInstagramPrompts: Record<string, string> = {\n`
for (const agent of agents) {
  output += `  ${agent.toUpperCase()}: \`${esc(instagramPrompts[agent])}\`,\n`
}
output += `}\n`

fs.writeFileSync(outFile, output, 'utf-8')

